spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
